---
title: "SD61 School Catchment Metrics"
output:
  xaringan::moon_reader:
    lib_dir: libs
    css: ["default", "default-fonts", "hygge"]
    nature:
      highlightStyle: github
      highlightLines: true
      countIncrementalSlides: false
      ratio: '16:9'
---


```{r setup, include=FALSE}
options(htmltools.dir.version = FALSE)
options(width = 90)
options(max_print = 5)

knitr::opts_chunk$set(
  dev = "ragg_png",
  collapse = TRUE,
  echo = FALSE,
  comment = "#>",
  warning = FALSE,
  message = FALSE,
  fig.path = "graphics/prod/figs",
  fig.width = 10,
  fig.height = 5,
  dpi = 300
)


library(targets)
library(tidyverse)
library(forcats)
library(bcdata)
library(plotly)

theme_set(
  theme_minimal() %+replace%
    theme(axis.title = element_blank())
  )
```



class: center, middle

## School District 61 Catchment Metrics

- Income data drawn from CensusMapper API

---
class: middle

## Income Range

```{r }
dat <- tar_read(median_income) %>%
  summarise(Min = min(var),
            Max = max(var)) %>%
  pivot_longer(cols = -School) %>% 
  filter(!is.na(value))

ordering <- dat %>% 
  filter(name == "Min") %>% 
  select(-name, order = value)

dat %>% 
  left_join(ordering, by = "School") %>% 
  ggplot(aes(x = value, y = fct_reorder(School, order, .desc = TRUE), colour = name, group = School)) +
  geom_line(colour = 'black') +
  geom_point() +
  scale_colour_viridis_d(end = 0.5) +
  guides(colour = FALSE) +
  labs(caption = cancensus::dataset_attribution("TX2018"))
```

---

## Percent of Population on Employment Assistance in Community

```{r}
tar_read(ei_benefits) %>% 
  filter(!is.na(var)) %>% 
  summarise(mean_ei_percent = mean(var)) %>% 
  ggplot(aes(x = mean_ei_percent, y = fct_reorder(School, mean_ei_percent))) +
  geom_col() +
  labs(caption = cancensus::dataset_attribution("TX2018"))
```

---

## Low Income Gap Ratio
```{r, fig.height=4}
tar_read(li_gap_ratio) %>% 
  filter(!is.na(var)) %>% 
  summarise(li_gap_ratio = mean(var)) %>% 
  ggplot(aes(x = li_gap_ratio, y = fct_reorder(School, li_gap_ratio))) +
  geom_col() +
  labs(caption = cancensus::dataset_attribution("TX2018"))
```

Reference: https://www150.statcan.gc.ca/n1/pub/75f0002m/2015001/low-faible-eng.htm
---

## Languages Spoken at Home

```{r}
ordering <- tar_read(language_by_school) %>% 
  filter(vector == "Not English or French") %>% 
  select(-vector, order = mean_prop)


tar_read(language_by_school) %>% 
  left_join(ordering, by = "School") %>% 
  ggplot(aes(y = fct_reorder(School, order), x = mean_prop, fill = vector)) +
  geom_col() +
  scale_fill_viridis_d(name = "Language", option = "mako", begin = 0.5) +
  labs(caption = cancensus::dataset_attribution("CA16"))
```

---

## George Jay School Population
```{r}
gj_school <- tar_read(school_popn_size) %>%
  filter(DISTRICT_NAME == "Greater Victoria") %>%
  filter(!is.na(SCHOOL_NAME)) %>%
  rowwise() %>%
  mutate(avg_class_size = mean(c(AVG_CLASS_SIZE_K, AVG_CLASS_SIZE_1_3, AVG_CLASS_SIZE_4_7, AVG_CLASS_SIZE_8_12), na.rm = TRUE)) %>%
  mutate(school_size = TOTAL_CLASSES*avg_class_size) %>%
  select(SCHOOL_YEAR, SCHOOL_NAME, school_size) %>%
  filter(grepl("Elementary", SCHOOL_NAME))

gj_school %>%
  ggplot(aes(x = SCHOOL_YEAR, y = school_size, group = SCHOOL_NAME)) +
  geom_line(colour = "gray80") +
  geom_line(data = filter(gj_school, SCHOOL_NAME == "George Jay Elementary"), colour = "0405FF", size = 1.5) +
  labs(y = "Estimated School Population", x = "School Year") +
  theme(axis.title = element_text())

```

